version: '3'

volumes:
  bundle:

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.dockerc:/home/root/.inputrc
    ports:
      - 3000
    stdin_open: true
    tty: true
